language: clojure
lein: lein2
before_install:
- npm install karma
script:
- lein midje
- lein2 cljsbuild once
- karma start --single-run --browsers PhantomJS
notifications:
  email:
    recipients:
      - z@caudate.me